package chat;


import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

public class Whisper_Frame extends javax.swing.JFrame {
    String name;
    Mainfun_Panel mainf ;
    Socket socket = null;
    DataInputStream in = null;
    DataOutputStream out = null;
    public Whisper_Frame(Mainfun_Panel mainf,String name) {
        super("正在和好友"+name);
        this.name =name;
        this.mainf = mainf;
        in = mainf.in;
        out = mainf.out;
        initComponents();
        jTextArea3.setEditable(false);
        jTextArea3.setLineWrap(true);
        jTextArea4.setLineWrap(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        jButton3.setText("聊天记录");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("关闭");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("发送");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane7.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton5))))
            .addComponent(jScrollPane7)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // inshow_LiaoTian();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        add_liaotian();
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if("".equals(jTextArea4.getText())){
            JOptionPane.showMessageDialog(null,  "发送消息不能为空！","提示信息", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date=new Date();
        String sdate=df.format(date);//获取当前系统时间
        String msg = mainf.user.name+"     "+sdate+"\n"+jTextArea4.getText().trim();//要连接数据库，只要登入成功，就可以记下用户的名字
        try {
            out.writeUTF("9 "+name+" "+msg);
            jTextArea3.append(msg+"\n");
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null,  "发送失败！","提示信息", JOptionPane.INFORMATION_MESSAGE);

        }
        jTextArea4.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed
    javax.swing.JTextArea getjTextArea3(){
        return jTextArea3;
    }
        
    void add_liaotian(){
         try { 
	     DocumentBuilderFactory factory=DocumentBuilderFactory.newInstance();
             DocumentBuilder domPaser= factory.newDocumentBuilder();
             org.w3c.dom.Document document;
             File file = new File("liaotian.xml");
             if(file.exists()){
             document = domPaser.parse(file);
             Element root=document.getDocumentElement() ;
             NodeList nodeList=root.getChildNodes();
             add(root,document);
             TransformerFactory transFactory=TransformerFactory.newInstance();
             Transformer transformer=transFactory.newTransformer();
             } 
             else{
	   //用java生成xml对应的Document
             document= domPaser.newDocument();
             document.setXmlVersion("1.0");
             Element root=document.createElement("聊天记录列表"); 
             document.appendChild(root); 
             add(root,document);
            
             }
          //将java对应的xml写入一个xml文件形式
  	    TransformerFactory transFactory=TransformerFactory.newInstance();
             Transformer transformer=transFactory.newTransformer();
             DOMSource  domSource=new DOMSource(document); //document为上面java所生成的
             //File file=new File("student.xml");
             FileOutputStream out=new FileOutputStream(file);
             StreamResult xmlResult=new StreamResult(out);
             transformer.transform(domSource, xmlResult);
             out.close();
             JOptionPane.showMessageDialog(null,"提交成功","提示信息", JOptionPane.INFORMATION_MESSAGE);
                
      }
      catch(Exception e){
             System.out.println(e);
      }
    }
    void add(Element root,org.w3c.dom.Document document){
       org.w3c.dom.Node elementNode=document.createElement("好友");
       org.w3c.dom.Node nodeTime=document.createElement("时间");
       org.w3c.dom.Node nodeTalk=document.createElement("聊天记录");
       nodeTalk.appendChild(document.createTextNode(jTextArea3.getText()));
       elementNode.appendChild(document.createTextNode(this.getTitle().trim()));
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        String sdate=df.format(date);
        nodeTime.appendChild(document.createTextNode(sdate));
        elementNode.appendChild(nodeTime);
        elementNode.appendChild(nodeTalk);
        root.appendChild(elementNode);
     }
 
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
